version: "3.9"
services:
  postgres:
    image: postgres:13.4
    mem_limit: 512m
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./sql:/mca-dashboard/sql
    ports: 
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    command: postgres -c listen_addresses='*'