version: "3.9"
services:
  pg:
    container_name: pg
    image: postgres:alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    command: postgres -c listen_addresses='*'

  rd:
    container_name: rd
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    ports:
      - $RD_PORT:$RD_PORT
    deploy:
      resources:
        limits:
          memory: 64M
    command: redis-server --appendonly yes

  # Still need to work on this. For now, I'll just leave this here while I work
  # on it.
  # web:
  #   container_name: web
  #   image: mb/dashboard
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/mca-dashboard
  #     - /app/node_modules
  #   ports:
  #     - $WEB_PORT:$WEB_PORT
  #     - $API_PORT:$API_PORT
  #   env_file: .env
  #   restart: on-failure
  #   depends_on:
  #     - pg
  #     - rd
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4096M

networks:
  dashboard:
    driver: bridge
