version: "3.9"
container_name: "metadmin_production"
services:
  web:
    container_name: web
    image: web
    build:
      context: ../
      dockerfile: ./apps/web/Dockerfile
    volumes:
      - ./:/apps/web
    ports:
      - $WEB_PORT:$WEB_PORT
      - $API_PORT:$API_PORT
    env_file: ./.env
    restart: on-failure
    depends_on:
      - pg
      - rd
    deploy:
      resources:
        limits:
          memory: 4096M
    command: yarn start
